version: "2"
services:
    rabbit:
      #container_name: rabbit
        image:
            rabbitmq
        ports:
          #    - "5672:5672"
            - "15672:15672"
        networks:
            cnalan:
                aliases:
                    - rabbit
    redis:
      #  container_name: redis
        image:
            redis
        #ports:
        #    - "6379:6379"
        networks:
            cnalan:
                aliases:
                    - redis
    mariadb:
      #  container_name: mariadb
        image:
            mariadb
        volumes:
          - ./microservices/i/dump/:/docker-entrypoint-initdb.d
        environment:
          - MYSQL_ROOT_PASSWORD=toto
          - MYSQL_DATABASE=prestashop
          - MYSQL_USER=prestashop
          - MYSQL_PASSWORD=prestashop1234
        networks:
            cnalan:
                aliases:
                    - mariadb
    web:
        build:
            context: web
        ports:
            - "80:80"
        links:
          - i
          - s
        networks:
            cnalan:
    i:
        build:
            context: microservices/i
        #ports:
        #    - "8080:8080"
        links:
            - mariadb
        networks:
            cnalan:
              aliases:
                - i
    s:
        build:
            context: microservices/s
        #ports:
        #    - "8081:8081"
        links:
            - redis
        networks:
            cnalan:
              aliases:
                - s
networks:
    cnalan:
        driver: bridge
