---
# This playbook deploys cna infra.  
- hosts: localhost
  #remote_user: root

  vars:
    - network: "10.0.1.0"
    - stackname: "psstack"

  tasks:
    - name: Get scale up url
      shell: openstack stack output show {{ stackname }} scale_dn_url -f json | jq ."output_value" | sed 's/"//g'
      register: supurl
     
    - name: Post to scale down url to trigger a node removal
      uri: 
        url: "{{ supurl.stdout }}"
        method: POST
