---
# tasks file for hostkeys
- name: Copy script to /tmp
  copy: src=files/get_private_ip.py dest=/tmp mode=u+x

- name: Get system ip using heat outputs
  command: echo {{ item }}
  register: sysip 
  with_lines: /tmp/get_private_ip.py '{{ stackname }}' '{{ stackoutput | to_json }}'

#- debug: msg="{{ sysip }}"

- name: Wait for instance to be ready
  wait_for: port=22 timeout=120 host={{ item.stdout }}
  delegate_to: bastion
  with_items:
    - "{{ sysip.results }}"

- name: Get new host keys
  command: ssh-keyscan -v -t rsa "{{ item.stdout }}"
  delegate_to: bastion
  register: hostkeys
  with_items:
    - "{{ sysip.results }}"

- name: Remove old host keys
  command: ssh-keygen -R "{{ item.stdout }}"
  with_items:
    - "{{ sysip.results }}"

- name: Register keys
  shell: echo "{{ item.stdout }}" >> ~/.ssh/known_hosts
  with_items:
    - "{{ hostkeys.results }}"
